name: fat32
description: FAT32 file system driver for Dart
version: 0.0.1
#homepage: https://www.example.com
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
